//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseworkDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsContain
    {
        public int ProductsContainID { get; set; }
        public int OrdersID { get; set; }
        public int ProductsID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
